"""Reading and writing a profile directory.

    profiles/lab-report/
      template.docx    the donor -- THE FORMAT ITSELF. Edit it in Word.
      overrides.yaml   your corrections. Hand-edited or written by sync.
      profile.json     generated by learn. Never hand-edit.
      evidence.json    generated -- the distributions behind every value.
      corpus.json      generated -- exemplar hashes, agreement, warnings.
      README.md        generated -- the format, in prose.

The split matters. Everything except `overrides.yaml` is regenerated from
scratch on every `learn`, so nothing a user typed can be lost by re-learning
with more exemplars -- and `overrides.yaml` is re-applied on top afterwards,
so their corrections survive it. Without that layering a user fixes something,
adds five exemplars, and their fix disappears with no message. That is the
failure mode that makes people stop trusting a tool, so it is built in from
the first version rather than retrofitted.

One honest limitation: PyYAML cannot round-trip comments. If `sync` has to
rewrite an `overrides.yaml` that contains comments, the original is copied to
`overrides.yaml.bak` first and the user is told, rather than the comments
vanishing silently.
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

import yaml

from ..analyze.stats import Vote
from ..learn.consensus import Consensus
from ..util.pointer import nest
from .schema import SCHEMA_VERSION, decode, encode, is_derived, round_trips

TEMPLATE = "template.docx"
OVERRIDES = "overrides.yaml"
PROFILE = "profile.json"
EVIDENCE = "evidence.json"
CORPUS = "corpus.json"
README = "README.md"

_HEADER = """\
# formgen overrides -- YOUR corrections to the learned format.
#
# This is the ONLY file in this directory that `formgen learn` will not
# overwrite. Everything pinned here is re-applied on top of the profile
# every time the format is re-learned, so corrections survive a bigger
# corpus.
#
# Most format corrections do NOT belong here: edit template.docx in Word
# instead and run `formgen profile sync`, which writes the pins for you.
# This file is for what has no representation in a .docx -- lint severity,
# tolerances, and placeholder types.
"""


def _json_dump(path: Path, document: Any) -> None:
    path.write_text(
        json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def _json_load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


# -- overrides ------------------------------------------------------------


@dataclass
class Pin:
    """One deliberate deviation from what the corpus said."""

    pointer: str
    value: Any
    pinned: str | None = None
    note: str | None = None
    source: str = "manual"      # "manual" | "sync"

    def as_dict(self) -> dict:
        out: dict[str, Any] = {"value": encode(self.value, self.pointer)}
        if self.pinned:
            out["pinned"] = self.pinned
        if self.note:
            out["note"] = self.note
        if self.source != "manual":
            out["source"] = self.source
        return out


@dataclass
class Overrides:
    pins: dict[str, Pin] = field(default_factory=dict)
    muted: set[str] = field(default_factory=set)
    severity: dict[str, str] = field(default_factory=dict)
    placeholders: dict[str, dict] = field(default_factory=dict)
    tolerances: dict[str, Any] = field(default_factory=dict)
    extra: dict[str, Any] = field(default_factory=dict)
    had_comments: bool = False

    @classmethod
    def load(cls, path: Path) -> Overrides:
        if not path.exists():
            return cls()
        text = path.read_text(encoding="utf-8-sig")
        raw = yaml.safe_load(text) or {}
        if not isinstance(raw, dict):
            raise ValueError(f"{path} must contain a mapping, not {type(raw).__name__}")
        known = {"version", "pins", "muted", "severity", "placeholders", "tolerances"}
        pins: dict[str, Pin] = {}
        for pointer, body in (raw.get("pins") or {}).items():
            if not isinstance(body, dict):
                body = {"value": body}
            pins[pointer] = Pin(
                pointer=pointer,
                value=decode(body.get("value"), pointer),
                pinned=body.get("pinned"),
                note=body.get("note"),
                source=body.get("source", "manual"),
            )
        return cls(
            pins=pins,
            muted=set(raw.get("muted") or ()),
            severity=dict(raw.get("severity") or {}),
            placeholders=dict(raw.get("placeholders") or {}),
            tolerances=dict(raw.get("tolerances") or {}),
            extra={k: v for k, v in raw.items() if k not in known},
            # Comments are the thing PyYAML cannot give back, so note their
            # presence now while we still have the original text.
            had_comments=any(
                line.lstrip().startswith("#") for line in text.splitlines()
            ),
        )

    def dump(self, path: Path) -> list[str]:
        """Write, backing the original up first if comments would be lost."""
        notes: list[str] = []
        if path.exists() and self.had_comments:
            backup = path.with_suffix(path.suffix + ".bak")
            shutil.copy2(path, backup)
            notes.append(
                f"{path.name} contained comments, which YAML round-tripping "
                f"cannot preserve; the original is at {backup.name}."
            )
        document: dict[str, Any] = {"version": 1}
        document.update(self.extra)
        if self.pins:
            document["pins"] = {
                p: self.pins[p].as_dict() for p in sorted(self.pins)
            }
        if self.muted:
            document["muted"] = sorted(self.muted)
        if self.severity:
            document["severity"] = dict(sorted(self.severity.items()))
        if self.placeholders:
            document["placeholders"] = dict(sorted(self.placeholders.items()))
        if self.tolerances:
            document["tolerances"] = dict(sorted(self.tolerances.items()))
        path.write_text(
            _HEADER + "\n" + yaml.safe_dump(
                document, sort_keys=False, default_flow_style=False,
                allow_unicode=True, width=100,
            ),
            encoding="utf-8",
        )
        return notes

    def add_pin(self, pointer: str, value: Any, note: str | None = None,
                source: str = "manual", today: str | None = None) -> Pin:
        pin = Pin(
            pointer=pointer,
            value=value,
            pinned=today or _dt.date.today().isoformat(),
            note=note,
            source=source,
        )
        self.pins[pointer] = pin
        return pin


@dataclass
class PinOutcome:
    """What happened to one pin when the profile was rebuilt."""

    pin: Pin
    status: str          # applied | redundant | overriding | unknown
    consensus_value: Any = None
    agreement: float = 0.0
    n_docs: int = 0

    def describe(self) -> str:
        shown = encode(self.pin.value, self.pin.pointer)
        if self.status == "unknown":
            return (
                f"{self.pin.pointer} = {shown} -- nothing in the corpus uses this "
                "property. Check the spelling; the pin has no effect."
            )
        theirs = encode(self.consensus_value, self.pin.pointer)
        when = f" (pinned {self.pin.pinned})" if self.pin.pinned else ""
        if self.status == "redundant":
            return (
                f"{self.pin.pointer} = {shown}{when}\n"
                f"    the corpus now agrees ({self.agreement:.0%} of "
                f"{self.n_docs}) -- pin is redundant, drop it?"
            )
        if self.status == "overriding":
            return (
                f"{self.pin.pointer} = {shown}{when}\n"
                f"    the corpus says {theirs} ({self.agreement:.0%} of "
                f"{self.n_docs}) -- pin still overrides. Keep?"
            )
        return f"{self.pin.pointer} = {shown}{when}"


def apply_overrides(
    consensus: Consensus, overrides: Overrides
) -> tuple[dict[str, Any], list[PinOutcome]]:
    """Layer pins on top of the learned values, reporting every interaction.

    Nothing here is silent. A pin the corpus has caught up with is reported as
    redundant, a pin the corpus contradicts is reported as still overriding,
    and a pin naming a property nobody uses is reported as probably a typo --
    because a correction that quietly stops mattering is as bad as one that
    quietly disappears.
    """
    values = {k: v.value for k, v in consensus.votes.items() if v.in_donor}
    outcomes: list[PinOutcome] = []
    for pointer in sorted(overrides.pins):
        pin = overrides.pins[pointer]
        vote = consensus.votes.get(pointer)
        if vote is None:
            outcomes.append(PinOutcome(pin, "unknown"))
            values[pointer] = pin.value
            continue
        same = vote.value == pin.value
        outcomes.append(
            PinOutcome(
                pin=pin,
                status="redundant" if same else "overriding",
                consensus_value=vote.value,
                agreement=vote.agreement,
                n_docs=vote.n_docs,
            )
        )
        values[pointer] = pin.value
    return values, outcomes


# -- the generated artifacts ----------------------------------------------


def _vote_row(vote: Vote, pinned: bool, severity: str | None) -> dict:
    return {
        "value": encode(vote.value, vote.key),
        "status": vote.status,
        # A derived value is reported, never enforced: linting it would either
        # restate the rule it was computed from or contradict it.
        "severity": "off" if is_derived(vote.key) else (severity or vote.severity),
        "coverage": round(vote.coverage, 4),
        "agreement": round(vote.agreement, 4),
        "observed_in": vote.observed_in,
        "of": vote.n_docs,
        "pinned": pinned,
        "weak": vote.weak,
    }


def write_profile(
    directory: Path,
    name: str,
    consensus: Consensus,
    overrides: Overrides,
    metas: Iterable[Any] = (),
    donor: Any = None,
    template_sha: str | None = None,
    generated: str | None = None,
    version: str = "0.1.0",
    skeleton: Any = None,
    role_styles: dict[str, str] | None = None,
) -> list[str]:
    """Write every generated artifact. Returns human-readable notes."""
    directory.mkdir(parents=True, exist_ok=True)
    values, outcomes = apply_overrides(consensus, overrides)
    pinned = {o.pin.pointer for o in outcomes}

    unstable = [p for p, v in values.items() if not round_trips(v, p)]
    if unstable:
        # Writing a value that cannot be read back would mean the next run
        # silently disagrees with this one. Refuse rather than corrupt.
        raise ValueError(
            "these values do not survive serialization and would change on "
            f"reload: {', '.join(sorted(unstable)[:5])}"
        )

    encoded = {p: encode(v, p) for p, v in values.items()}
    rules = {
        p: _vote_row(v, p in pinned, overrides.severity.get(p))
        for p, v in sorted(consensus.votes.items())
        if v.in_donor and p not in overrides.muted
    }
    for pointer in pinned:
        if pointer in rules:
            rules[pointer]["value"] = encoded[pointer]

    _json_dump(directory / PROFILE, {
        "schema": SCHEMA_VERSION,
        "name": name,
        "generator": f"formgen {version}",
        "generated": generated or _dt.datetime.now().isoformat(timespec="seconds"),
        # A count, not the names: profile.json travels with the format, and
        # an exemplar's file name can say more about a programme than the
        # format ever does. corpus.json and evidence.json name them.
        "corpus": {"count": len(consensus.docs)},
        # The donor's hash, so `sync` can tell "the user edited template.docx"
        # from "the user did not" without diffing the whole package.
        "template": {"sha256": template_sha},
        "format": nest(encoded),
        "rules": rules,
        # The structural half of the profile: which sections every document
        # has, what text is fixed, and where the fields are. Absent until
        # `learn` has enough exemplars to align, and that absence is the
        # honest answer rather than a skeleton inferred from two documents.
        "skeleton": skeleton.as_json() if skeleton is not None else None,
        # role -> the style in template.docx that implements it. Recorded
        # rather than derived, because `apply` points w:pStyle at whatever
        # this says: a name we assumed the donor defined but it does not is
        # a paragraph that silently takes Word's own built-in definition,
        # which differs by version and by locale.
        "role_styles": dict(sorted((role_styles or {}).items())),
    })

    _json_dump(directory / EVIDENCE, {
        pointer: {
            "value": encode(vote.value, pointer),
            "agreeing": list(vote.agreeing),
            "dissenting": list(vote.dissenting),
            "silent": list(vote.silent),
            "alternatives": [
                {"value": encode(raw, pointer), "documents": count}
                for _, count, raw in vote.alternatives
            ],
            "internal_agreement": {
                dv.doc: round(dv.internal_agreement, 4) for dv in vote.per_doc
            },
        }
        for pointer, vote in sorted(consensus.votes.items())
    })

    _json_dump(directory / CORPUS, {
        "documents": [_meta_row(m, consensus) for m in metas],
        "warnings": list(consensus.warnings),
        "outliers": list(consensus.outliers),
        "split": (
            {
                "strength": round(consensus.split.strength, 3),
                "groups": [
                    {"medoid": c.medoid, "members": list(c.members)}
                    for c in consensus.split.clusters
                ],
            }
            if consensus.split else None
        ),
        "donor": getattr(donor, "doc", None),
    })

    (directory / README).write_text(
        render_readme(name, consensus, encoded, outcomes, donor),
        encoding="utf-8",
    )
    # Write overrides.yaml whenever there is something in it to correct --
    # inferred placeholders included. Their type, pattern and required-ness
    # are exactly the knobs the file exists for, and a user cannot turn a
    # knob that is not written down.
    has_content = bool(overrides.pins or overrides.placeholders)
    notes = (overrides.dump(directory / OVERRIDES)
             if has_content or (directory / OVERRIDES).exists() else [])
    return notes


def _meta_row(meta: Any, consensus: Consensus) -> dict:
    return {
        "id": meta.doc,
        "paragraphs": meta.paragraphs,
        "runs": meta.runs,
        "direct_formatting": round(meta.direct_density, 4),
        "styles_used": list(meta.styles_used),
        "sections": meta.section_count,
        "headers": meta.header_parts,
        "footers": meta.footer_parts,
        "agreement": round(consensus.agreement_by_doc.get(meta.doc, 0.0), 4),
        "disqualified": list(meta.disqualified),
        "sha256": getattr(meta, "sha256", None),
    }


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 16), b""):
            digest.update(chunk)
    return digest.hexdigest()


def render_readme(
    name: str,
    consensus: Consensus,
    encoded: dict[str, Any],
    outcomes: list[PinOutcome],
    donor: Any = None,
) -> str:
    lines = [
        f"# {name}",
        "",
        f"Learned from {len(consensus.docs)} document(s). "
        "`corpus.json` names them and `evidence.json` records which of them "
        "voted for each value; neither is needed to use the format, so "
        "delete both before sharing this profile if the file names are "
        "themselves sensitive.",
        "",
        "`template.docx` **is** the format. To change it, open it in Word, "
        "edit it the way you would edit any document, and run "
        "`formgen profile sync`.",
        "",
    ]
    if donor is not None:
        # Deliberately without the donor's file name, which is the most
        # revealing of the lot: it names the one document template.docx is
        # a copy of. The score is what a reader needs to judge the choice.
        lines += [f"Donor: {donor.explain().split(':', 1)[-1].strip()}", ""]

    if consensus.warnings:
        lines += ["## Read this first", ""]
        lines += [f"- {w}" for w in consensus.warnings] + [""]

    enforced = consensus.enforceable()
    lines += [
        "## What lint enforces",
        "",
        f"{len(enforced)} of {len(consensus.votes)} learned properties are "
        "enforced; the rest were too rare or too contested to be worth a rule.",
        "",
        "| property | value | status | agreement |",
        "|---|---|---|---|",
    ]
    for pointer, vote in sorted(enforced.items())[:40]:
        lines.append(
            f"| `{pointer}` | {encoded.get(pointer, encode(vote.value, pointer))} "
            f"| {vote.status} | {vote.agreement:.0%} of {vote.observed_in} |"
        )
    if len(enforced) > 40:
        lines.append(f"| ... | _{len(enforced) - 40} more in profile.json_ | | |")
    lines.append("")

    review = consensus.needs_review()
    if review:
        lines += [
            "## Needs review",
            "",
            "These had no clear majority. Fix them in `template.docx` and run "
            "`formgen profile sync`, or leave them -- they lint as warnings "
            "or not at all.",
            "",
        ]
        for pointer, vote in sorted(review.items()):
            alternatives = ", ".join(
                f"{encode(raw, pointer)} ({count})" for _, count, raw in vote.alternatives
            )
            lines.append(
                f"- `{pointer}`: {encode(vote.value, pointer)} "
                f"({vote.modal_count}/{vote.observed_in})"
                + (f" vs {alternatives}" if alternatives else "")
            )
        lines.append("")

    if outcomes:
        lines += ["## Your pins", ""]
        lines += [f"- {o.describe()}" for o in outcomes] + [""]
    return "\n".join(lines)


def read_profile(directory: Path) -> dict:
    return _json_load(Path(directory) / PROFILE)


# -- the loaded, typed view -----------------------------------------------


@dataclass
class Profile:
    """A profile directory, loaded and typed, as the linter consumes it."""

    directory: Path
    name: str = ""
    rules: dict[str, dict] = field(default_factory=dict)
    overrides: Overrides = field(default_factory=Overrides)
    corpus: dict = field(default_factory=dict)
    template_sha: str | None = None
    skeleton: dict = field(default_factory=dict)
    role_styles: dict = field(default_factory=dict)

    @classmethod
    def load(cls, directory: Path) -> Profile:
        directory = Path(directory)
        document = read_profile(directory)
        return cls(
            directory=directory,
            name=document.get("name") or directory.name,
            rules=document.get("rules") or {},
            overrides=Overrides.load(directory / OVERRIDES),
            corpus=document.get("corpus") or {},
            template_sha=(document.get("template") or {}).get("sha256"),
            skeleton=document.get("skeleton") or {},
            role_styles=document.get("role_styles") or {},
        )

    @property
    def template(self) -> Path:
        return self.directory / TEMPLATE

    def slots(self, kind: str | None = None) -> list[dict]:
        rows = self.skeleton.get("slots") or []
        return [r for r in rows if kind is None or r.get("kind") == kind]

    def required_sections(self) -> list[dict]:
        """Headings in the order the corpus puts them, skipping optional ones.

        Lint checks order against this, and only against the confident part
        of it: a section present in 60% of exemplars is as likely to be
        optional as forgotten, and a rule built on that guess fires on
        documents that are fine.
        """
        return [
            r for r in self.slots()
            if r.get("heading") and not r.get("optional")
        ]

    def value(self, pointer: str, default: Any = None) -> Any:
        rule = self.rules.get(pointer)
        if rule is None:
            return default
        return decode(rule.get("value"), pointer)

    def severity(self, pointer: str) -> str:
        """Lint severity, with overrides.yaml having the last word.

        Muting is expressed here rather than by deleting the rule, so a muted
        property still shows in `profile show` with its learned value -- the
        user can see what they switched off.
        """
        if pointer in self.overrides.muted:
            return "off"
        if pointer in self.overrides.severity:
            return self.overrides.severity[pointer]
        rule = self.rules.get(pointer)
        return rule.get("severity", "off") if rule else "off"

    def status(self, pointer: str) -> str:
        rule = self.rules.get(pointer)
        return rule.get("status", "informational") if rule else "informational"

    def pointers_under(self, prefix: str) -> list[str]:
        from ..util.pointer import under

        return under(self.rules.keys(), prefix)

    @property
    def style_names(self) -> set[str]:
        out: set[str] = set()
        for pointer in self.rules:
            parts = pointer.split("/")
            if len(parts) > 4 and parts[1] == "styles":
                out.add(parts[3])
        return out

    def roles(self) -> set[str]:
        """Roles the corpus had an opinion about, however it was expressed.

        On a corpus with no styles this is the only place the format lives:
        every paragraph was `Normal`, so `/styles/...` learned one bucket and
        `/roles/...` learned the title, the headings and the body apart.
        """
        out: set[str] = set()
        for pointer in self.rules:
            parts = pointer.split("/")
            if len(parts) > 2 and parts[1] == "roles":
                out.add(parts[2])
        return out

    @property
    def placeholders(self) -> dict[str, dict]:
        return self.overrides.placeholders

    def required_placeholders(self) -> set[str]:
        return {
            name for name, body in self.placeholders.items()
            if body.get("required", True)
        }
