"""Document-order traversal of every block in a package.

Naive iteration over the direct children of w:body misses a great deal of real
content: paragraphs inside tables, content controls, text boxes, tracked
changes, headers, footers and footnotes. Anything missed here is content the
linter never checks and the reformatter never restyles, so the walker is
deliberately exhaustive and every skip is a decision, not an oversight.

The structural traps handled here, each of which silently loses or duplicates
real content:

* **Rows and cells can be wrapped.** ``w:tbl`` holds EG_ContentRowContent, not
  just ``w:tr``: a row may be wrapped in ``w:sdt`` (Word's repeating-section
  control, which every form template uses) or ``w:customXml``, and the same
  goes for cells inside ``w:tr``. Filtering with ``findall(w:tr)`` loses whole
  table bodies.
* **mc:AlternateContent** duplicates content across branches. Exactly one is
  taken, and it is the first ``mc:Choice`` whose ``Requires`` namespaces we
  actually understand -- not simply the first.
* **Tracked changes cut both ways.** ``w:moveTo`` is the *destination* of a
  move and is visible text; ``w:moveFrom`` is the source and its runs carry
  ordinary ``w:t``, so recursing into it double-counts the moved sentence.
* **Field instructions split across runs**: ``DOCPROP`` + ``ERTY "Proj`` +
  ``ectNumber"``. Instructions are reassembled before anyone matches them.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass, replace

from lxml import etree

from ..opc.ns import NS, RT, qn
from ..opc.package import OpcPackage

# Namespaces whose mc:Choice content we can actually interpret.
MC_UNDERSTOOD = {
    NS["w"], NS["w14"], NS["w15"], NS["wps"], NS["wpg"], NS["wp"], NS["wp14"],
    NS["v"], NS["o"], NS["a"], NS["pic"], NS["m"], NS["w16se"],
}

# Wrappers that contribute no structure of their own: their children belong to
# the enclosing container, and must continue its numbering (see `counts`).
TRANSPARENT = {qn("w:customXml")}
INSERTED = {qn("w:ins"), qn("w:moveTo")}      # visible content
DELETED = {qn("w:del"), qn("w:moveFrom")}     # not visible, but still blocks

# Run children that carry visible text but are not w:t.
_TAB_LIKE = {qn("w:tab"), qn("w:ptab")}
_BREAK_LIKE = {qn("w:br"), qn("w:cr")}
# Reference marks are generated by Word, not stored, so they contribute
# nothing to text -- but they must be recognised rather than fall through.
_EMPTY_MARKS = {
    qn("w:footnoteRef"), qn("w:endnoteRef"), qn("w:annotationRef"),
    qn("w:separator"), qn("w:continuationSeparator"), qn("w:pgNum"),
    qn("w:lastRenderedPageBreak"), qn("w:softHyphen"),
}
_DATE_PARTS = {
    qn("w:dayShort"), qn("w:monthShort"), qn("w:yearShort"),
    qn("w:dayLong"), qn("w:monthLong"), qn("w:yearLong"),
}
# Wrappers around runs that must be descended for text.
_RUN_WRAPPERS = {
    qn("w:r"), qn("w:hyperlink"), qn("w:ins"), qn("w:moveTo"), qn("w:smartTag"),
    qn("w:sdt"), qn("w:sdtContent"), qn("w:fldSimple"), qn("w:bdo"), qn("w:dir"),
    qn("w:customXml"), qn("w:ruby"), qn("w:rubyBase"), qn("w:rt"),
}

OBJ = "￼"  # OBJECT REPLACEMENT CHARACTER, for content we cannot render


@dataclass(frozen=True)
class Context:
    """Where a block lives. Drives both classification and the lint locator."""

    part: str
    kind: str = "body"
    table_depth: int = 0
    row: int | None = None
    col: int | None = None
    in_sdt: bool = False
    in_textbox: bool = False
    in_ins: bool = False
    in_del: bool = False          # inside a deletion or a move source
    is_placeholder: bool = False  # sdt showing its greyed prompt text
    sdt_tag: str | None = None

    def describe(self) -> str:
        """Human-readable container, for the lint locator."""
        if self.kind == "table":
            where = f"table row {self.row}, column {self.col}"
            return where if self.table_depth == 1 else f"{where} (nested {self.table_depth} deep)"
        if self.kind in ("header", "footer", "footnote", "endnote", "comment"):
            return self.kind
        if self.in_textbox:
            return "text box"
        if self.in_sdt:
            return f"content control {self.sdt_tag!r}" if self.sdt_tag else "content control"
        return "body"


@dataclass
class Block:
    """One block-level element (a paragraph or a table) in document order."""

    element: etree._Element
    kind: str                  # "p" | "tbl" | "oMathPara" | "altChunk"
    path: str                  # structural coordinate, unique within the walk
    context: Context
    index: int = 0

    @property
    def is_paragraph(self) -> bool:
        return self.kind == "p"

    @property
    def text(self) -> str:
        """Visible text.

        For a table this is a convenience view that OVERLAPS the cell
        paragraphs, which are separate blocks in their own right. Never
        concatenate blocks of mixed kind, or table text is counted twice.
        """
        if self.kind == "tbl":
            return table_text(self.element)
        if self.kind == "altChunk":
            return ""
        return paragraph_text(self.element)

    @property
    def para_id(self) -> str | None:
        """w14:paraId -- a better address than a positional path when present.

        Not durable: Word regenerates these across a document after some
        operations, so it is the primary address within one read, never a
        cross-session key. It is also how commentsExtended.xml attaches a
        comment to its paragraph.
        """
        return self.element.get(qn("w14:paraId"))

    @property
    def style_id(self) -> str | None:
        if self.kind == "tbl":
            tbl_style = self.element.find(f"{qn('w:tblPr')}/{qn('w:tblStyle')}")
            return tbl_style.get(qn("w:val")) if tbl_style is not None else None
        pstyle = self.element.find(f"{qn('w:pPr')}/{qn('w:pStyle')}")
        return pstyle.get(qn("w:val")) if pstyle is not None else None


# -- markup compatibility -------------------------------------------------


def _understood(choice: etree._Element) -> bool:
    """Can we interpret every namespace this mc:Choice requires?"""
    required = (choice.get("Requires") or "").split()
    nsmap = choice.nsmap
    # Requires holds PREFIXES, which are file-local: resolve them to URIs.
    return all(nsmap.get(prefix) in MC_UNDERSTOOD for prefix in required)


def _mc_branch(el: etree._Element) -> etree._Element | None:
    """Pick exactly one branch: the first understood Choice, else Fallback."""
    for choice in el.findall(qn("mc:Choice")):
        if _understood(choice):
            return choice
    return el.find(qn("mc:Fallback"))


def _find_textboxes(el: etree._Element) -> list[etree._Element]:
    """Collect w:txbxContent under `el`, descending only one mc branch."""
    found: list[etree._Element] = []
    for child in el:
        if not isinstance(child.tag, str):
            continue
        if child.tag == qn("mc:AlternateContent"):
            if (branch := _mc_branch(child)) is not None:
                found.extend(_find_textboxes(branch))
        elif child.tag == qn("w:txbxContent"):
            found.append(child)
        elif len(child):
            found.extend(_find_textboxes(child))
    return found


# -- text extraction -----------------------------------------------------


def _sym_char(el: etree._Element) -> str:
    """A w:sym renders a real glyph from a symbol font.

    Mapping it properly needs per-font tables (Symbol, Wingdings) that we do
    not carry, so we emit a placeholder rather than nothing: dropping it
    silently drifts every character-count invariant.
    """
    return OBJ


def _iter_text_nodes(el: etree._Element):
    """Yield visible text pieces, descending through run wrappers."""
    for child in el:
        tag = child.tag
        if not isinstance(tag, str):
            continue
        if tag == qn("mc:AlternateContent"):
            branch = _mc_branch(child)
            # An anchored shape is walked as its own block; descending here
            # would duplicate it. Anything else in an alternate branch is
            # genuinely inline (symbol swaps, extension-wrapped runs) and
            # must be emitted or the text silently disappears.
            if branch is not None and not _find_textboxes(branch):
                yield from _iter_text_nodes(branch)
        elif tag == qn("w:t"):
            yield child.text or ""
        elif tag == qn("m:t"):
            yield child.text or ""          # Office Math carries real text
        elif tag in _TAB_LIKE:
            yield "\t"
        elif tag in _BREAK_LIKE:
            yield "\n"
        elif tag == qn("w:noBreakHyphen"):
            yield "-"
        elif tag == qn("w:sym"):
            yield _sym_char(child)
        elif tag in _EMPTY_MARKS or tag in _DATE_PARTS:
            continue
        elif tag in (qn("w:delText"), qn("w:instrText")):
            continue                        # deleted text and field codes
        elif tag in DELETED:
            continue                        # move source: its runs use w:t
        elif tag == qn("w:txbxContent"):
            continue                        # a separate block
        elif tag in _RUN_WRAPPERS or tag.startswith(f"{{{NS['m']}}}"):
            yield from _iter_text_nodes(child)


def paragraph_text(p: etree._Element) -> str:
    return "".join(_iter_text_nodes(p))


def table_text(tbl: etree._Element) -> str:
    return " ".join(paragraph_text(p) for p in tbl.iter(qn("w:p"))).strip()


def iter_runs(p: etree._Element):
    """Yield every w:r in a paragraph, including those inside wrappers."""
    for child in p:
        if not isinstance(child.tag, str):
            continue
        if child.tag == qn("w:r"):
            yield child
        elif child.tag == qn("mc:AlternateContent"):
            if (branch := _mc_branch(child)) is not None:
                yield from iter_runs(branch)
        elif child.tag in _RUN_WRAPPERS:
            yield from iter_runs(child)


def field_instructions(p: etree._Element) -> list[str]:
    """Every field instruction in a paragraph, reassembled across runs."""
    found: list[str] = []
    for simple in p.iter(qn("w:fldSimple")):
        if instr := simple.get(qn("w:instr")):
            found.append(" ".join(instr.split()))

    depth = 0
    buffer: list[str] = []
    for run in iter_runs(p):
        for child in run:
            if child.tag == qn("w:fldChar"):
                kind = child.get(qn("w:fldCharType"))
                if kind == "begin":
                    depth += 1
                    if depth == 1:
                        buffer = []
                elif kind in ("separate", "end") and depth:
                    if depth == 1 and buffer:
                        found.append(" ".join("".join(buffer).split()))
                        buffer = []
                    if kind == "end":
                        depth -= 1
            elif child.tag == qn("w:instrText") and depth:
                buffer.append(child.text or "")
    return [f for f in found if f]


# -- normalization -------------------------------------------------------

_WS = re.compile(r"\s+")
_DASHES = dict.fromkeys(
    [0x2010, 0x2011, 0x2012, 0x2013, 0x2014, 0x2015, 0x2212], "-"
)
_QUOTES = {
    0x2018: "'", 0x2019: "'", 0x201A: "'", 0x201B: "'",
    0x201C: '"', 0x201D: '"', 0x201E: '"', 0x00AB: '"', 0x00BB: '"',
    0x2026: "...",
}
_TOLERANT = {**_DASHES, **_QUOTES, 0x00AD: None}


def _strip_format_chars(text: str) -> str:
    """Remove Unicode Cf characters.

    Zero-width spaces, directional marks and stray BOMs are invisible and
    arrive from pasted-from-web text and from Word's own bidi handling. Left
    in, they make an exact boilerplate match fail for no visible reason.
    """
    return "".join(c for c in text if unicodedata.category(c) != "Cf")


def match_key(text: str) -> str:
    """Tolerant key, for FINDING a block.

    Folds dash and quote variants, ligatures and full-width forms, so a
    boilerplate paragraph is recognised despite cosmetic differences. Case is
    deliberately preserved: "DISTRIBUTION STATEMENT A" and its lowercase form
    are not the same statement.
    """
    folded = unicodedata.normalize("NFKC", _strip_format_chars(text))
    return _WS.sub(" ", folded.translate(_TOLERANT)).strip()


def exact_key(text: str) -> str:
    """Strict key, for VERIFYING a block matches required wording.

    NFC only: it keeps the characters distinct so a report can say *which*
    character is wrong. Use match_key to locate the paragraph, then this to
    enforce it -- a distribution statement with the wrong dash should fail,
    not quietly pass.
    """
    normalized = unicodedata.normalize("NFC", _strip_format_chars(text))
    return _WS.sub(" ", normalized).strip()


def normalize_text(text: str) -> str:
    """Backwards-compatible alias for :func:`match_key`."""
    return match_key(text)


# -- traversal -----------------------------------------------------------


def _iter_rows(tbl: etree._Element):
    """Rows of a table, expanding sdt/customXml/revision wrappers."""
    for child in tbl:
        if not isinstance(child.tag, str):
            continue
        if child.tag == qn("w:tr"):
            yield child
        elif child.tag == qn("w:sdt"):
            if (content := child.find(qn("w:sdtContent"))) is not None:
                yield from _iter_rows(content)
        elif child.tag in TRANSPARENT | INSERTED | DELETED:
            yield from _iter_rows(child)


def _iter_cells(row: etree._Element):
    """Cells of a row, expanding sdt/customXml/revision wrappers."""
    for child in row:
        if not isinstance(child.tag, str):
            continue
        if child.tag == qn("w:tc"):
            yield child
        elif child.tag == qn("w:sdt"):
            if (content := child.find(qn("w:sdtContent"))) is not None:
                yield from _iter_cells(content)
        elif child.tag in TRANSPARENT | INSERTED | DELETED:
            yield from _iter_cells(child)


class Walker:
    """Yields every block in a package, in reading order."""

    def __init__(self, pkg: OpcPackage):
        self.pkg = pkg
        self._counter = 0

    def blocks(self, include_aux: bool = True) -> list[Block]:
        self._counter = 0
        out: list[Block] = []
        main = self.pkg.main_document
        body = self.pkg.element(main).find(qn("w:body"))
        if body is not None:
            out.extend(self._walk(body, "body", Context(part=main)))
        if include_aux:
            out.extend(self._aux_blocks())
        return out

    def _aux_blocks(self) -> list[Block]:
        out: list[Block] = []
        for reltype, kind in (("footnotes", "footnote"), ("endnotes", "endnote")):
            part = self.pkg.related(RT[reltype])
            if not part or part not in self.pkg:
                continue
            root = self.pkg.element(part)
            for note in root.findall(qn(f"w:{kind}")):
                # Filter on w:type, not on id. The -1/0 convention is Word's
                # habit, not a rule: other producers number the first real
                # note 0, and some emit a continuationNotice with a positive
                # id. Filtering by id both drops real notes and leaks
                # separators into the text.
                if (note.get(qn("w:type")) or "normal") != "normal":
                    continue
                nid = note.get(qn("w:id")) or "?"
                out.extend(self._walk(note, f"{kind}[{nid}]",
                                      Context(part=part, kind=kind)))
        for reltype, kind in (("header", "header"), ("footer", "footer")):
            # dict.fromkeys dedupes: two relationships to one part would
            # otherwise walk it twice.
            for part in dict.fromkeys(self.pkg.related_all(RT[reltype])):
                if part not in self.pkg:
                    continue
                out.extend(self._walk(self.pkg.element(part), kind,
                                      Context(part=part, kind=kind)))
        return out

    def _walk(
        self,
        parent: etree._Element,
        path: str,
        ctx: Context,
        counts: dict[str, int] | None = None,
    ) -> list[Block]:
        out: list[Block] = []
        # Transparent wrappers share the parent's counter so that a paragraph
        # inside w:ins continues the body's numbering -- both to keep paths
        # unique and to match what a human counts in Word.
        own = counts if counts is not None else {}
        for child in parent:
            tag = child.tag
            if not isinstance(tag, str):
                continue
            if tag == qn("w:p"):
                n = own["p"] = own.get("p", 0) + 1
                p_path = f"{path}/p[{n}]"
                out.append(self._block(child, "p", p_path, ctx))
                out.extend(self._walk_textboxes(child, p_path, ctx))
            elif tag == qn("w:tbl"):
                n = own["tbl"] = own.get("tbl", 0) + 1
                tbl_path = f"{path}/tbl[{n}]"
                out.append(self._block(child, "tbl", tbl_path, ctx))
                out.extend(self._walk_table(child, tbl_path, ctx))
            elif tag == qn("w:sdt"):
                content = child.find(qn("w:sdtContent"))
                if content is not None:
                    n = own["sdt"] = own.get("sdt", 0) + 1
                    out.extend(self._walk(content, f"{path}/sdt[{n}]",
                                          self._enter_sdt(child, ctx)))
            elif tag in INSERTED:
                out.extend(self._walk(child, path, replace(ctx, in_ins=True), own))
            elif tag in DELETED:
                # Not visible, but still a block: a reformatter that never
                # sees it leaves stale formatting that reappears the moment a
                # reviewer clicks Reject.
                out.extend(self._walk(child, path, replace(ctx, in_del=True), own))
            elif tag in TRANSPARENT:
                out.extend(self._walk(child, path, ctx, own))
            elif tag == qn("mc:AlternateContent"):
                if (branch := _mc_branch(child)) is not None:
                    out.extend(self._walk(branch, path, ctx, own))
            elif tag == qn("w:txbxContent"):
                out.extend(self._walk(child, f"{path}/txbx",
                                      replace(ctx, in_textbox=True, kind="textbox")))
            elif tag == qn("m:oMathPara"):
                n = own["math"] = own.get("math", 0) + 1
                out.append(self._block(child, "oMathPara", f"{path}/math[{n}]", ctx))
            elif tag == qn("w:altChunk"):
                # Word imports and renders this part inline; we cannot inspect
                # or restyle it. Emitting a block means lint can refuse to
                # certify the document rather than silently passing it.
                n = own["altChunk"] = own.get("altChunk", 0) + 1
                out.append(self._block(child, "altChunk",
                                       f"{path}/altChunk[{n}]", ctx))
            elif len(child):
                out.extend(self._walk_textboxes(child, path, ctx))
        return out

    def _walk_table(self, tbl: etree._Element, path: str, ctx: Context) -> list[Block]:
        out: list[Block] = []
        for r, row in enumerate(_iter_rows(tbl), 1):
            for c, cell in enumerate(_iter_cells(row), 1):
                cell_ctx = replace(
                    ctx, kind="table", table_depth=ctx.table_depth + 1, row=r, col=c
                )
                out.extend(self._walk(cell, f"{path}/tr[{r}]/tc[{c}]", cell_ctx))
        return out

    def _walk_textboxes(self, el: etree._Element, path: str, ctx: Context) -> list[Block]:
        out: list[Block] = []
        box_ctx = replace(ctx, in_textbox=True, kind="textbox")
        for i, box in enumerate(_find_textboxes(el), 1):
            out.extend(self._walk(box, f"{path}/txbx[{i}]", box_ctx))
        return out

    @staticmethod
    def _enter_sdt(sdt: etree._Element, ctx: Context) -> Context:
        pr = sdt.find(qn("w:sdtPr"))
        tag = None
        placeholder = False
        if pr is not None:
            for name in ("w:tag", "w:alias"):
                el = pr.find(qn(name))
                if el is not None and el.get(qn("w:val")):
                    tag = el.get(qn("w:val"))
                    break
            # An empty control holds Word's greyed prompt text. Treating that
            # as content makes a linter conclude the field is filled in.
            placeholder = pr.find(qn("w:showingPlcHdr")) is not None
        return replace(ctx, in_sdt=True, sdt_tag=tag or ctx.sdt_tag,
                       is_placeholder=placeholder)

    def _block(self, el, kind: str, path: str, ctx: Context) -> Block:
        self._counter += 1
        return Block(element=el, kind=kind, path=path, context=ctx, index=self._counter)


def walk(pkg: OpcPackage, include_aux: bool = True) -> list[Block]:
    return Walker(pkg).blocks(include_aux=include_aux)


def document_text(pkg: OpcPackage, include_aux: bool = True) -> str:
    """All visible text, for the text-preservation invariant.

    Excludes tables (their cells are separate blocks), deleted content, and
    content-control placeholder prompts -- none of which a reader sees as
    document text.
    """
    return "\n".join(
        b.text for b in walk(pkg, include_aux)
        if b.is_paragraph
        and not b.context.in_del
        and not b.context.is_placeholder
        and b.text.strip()
    )


def has_alt_chunks(pkg: OpcPackage) -> bool:
    """Does this document import content we cannot inspect?"""
    return any(b.kind == "altChunk" for b in walk(pkg))
